# Generated by Django 3.0.5 on 2020-05-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corememapp', '0002_auto_20200501_2214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memory',
            old_name='bodytext',
            new_name='story',
        ),
        migrations.AddField(
            model_name='memory',
            name='category',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='memory',
            name='when',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='memory',
            name='where',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='memory',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
